name: cpp_kg
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  # data handling
  - pandas
  - numpy
  # deep learning
  - pytorch::pytorch
  - tqdm
  # HTTP / preprocessing
  - requests
  - matplotlib
  # web app
  - conda-forge::flask
  # ontology / RDF
  - rdflib
  - jpype1
  # Java runtime for JPype / OWLAPI
  - conda-forge::openjdk
  # HuggingFace
  - conda-forge::transformers
  # pip-only packages
  - pip:
    - mowl-borg
    - pyshex
    - pronto
    - rapidfuzz
    - faiss-cpu
    - pyld
