name: cpp_kg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  # data handling
  - pandas
  - numpy
  # utilities
  - tqdm
  # HTTP / preprocessing
  - requests
  - matplotlib
  # web app
  - conda-forge::flask
  # ontology / RDF
  - rdflib
  - jpype1
  # HuggingFace
  - conda-forge::transformers
  # pip-only packages
  - pip:
    - torch
    - mowl-borg
    - pyshex
    - pronto
    - rapidfuzz
    - faiss-cpu
    - pyld
    - pydantic
    - ollama
